#!/usr/bin/env python3
"""
P8 Release Readiness Report Generator
运行回归测试后生成 release-readiness.json 和对应 Markdown。

用法:
    python3 release_readiness.py \
        --runs-dir "$RUNS" \
        --vault-dir "$VAULT" \
        --run-id "$RUN_ID" \
        --port "$PORT" \
        --trace "$TRACE"
"""

import argparse
import json
import os
import sys
from pathlib import Path
from datetime import datetime, timezone
from regression_harness import (
    check_files,
    check_apis,
    check_dashboard_build,
    check_trace,
    check_sample_run,
    DASHBOARD_JS_BUILD_KEY,
)

READINESS_SCHEMA = "ai-judge-release-readiness-v1"
PRODUCT_DIR = str(Path(__file__).resolve().parent)


def _build_check_summary(check_result: dict) -> dict:
    """Extract summary fields from a check dict for JSON embedding."""
    return {
        "ok": check_result.get("ok", False),
        "blockers": check_result.get("blockers", []),
        "warnings": check_result.get("warnings", []),
        "details": {k: v for k, v in check_result.items()
                    if k not in ("ok", "blockers", "warnings")},
    }


def _emoji(ok: bool) -> str:
    return ":white_check_mark:" if ok else ":x:"


def _build_markdown(report: dict) -> str:
    lines: list[str] = []
    lines.append("# AI Judge Release Readiness")
    lines.append("")
    overall = report["overall_status"]
    icon = _emoji(overall == "pass")
    lines.append(f"## Overall Status: {icon} **{overall.upper()}**")
    lines.append(f"> Generated: {report['generated_at']}")
    lines.append(f"> Sample Run: `{report['sample_run_id']}`")
    lines.append(f"> Build ID: `{report['build_id']}`")
    lines.append("")

    # Core Artifacts
    lines.append("## Core Artifacts")
    files = report["checks"]["files"]["details"]
    for group_label, group_key in [("Run Files", "run_files"),
                                   ("Global Files", "global_files"),
                                   ("Vault Indexes", "vault_files")]:
        lines.append(f"### {group_label}")
        for fname, exists in files.get(group_key, {}).items():
            lines.append(f"- {_emoji(exists)} `{fname}`")
    lines.append("")

    # Core APIs
    lines.append("## Core APIs")
    apis = report["checks"]["apis"]["details"]["endpoints"]
    for label, info in apis.items():
        lines.append(f"- {_emoji(info['ok'])} `{label}` → {info['status']}")
    lines.append("")

    # Dashboard Build
    lines.append("## Dashboard Build")
    db = report["checks"]["dashboard_build"]
    lines.append(f"- {_emoji(db['ok'])} BUILD_ID: `{report['build_id']}`")
    if db["ok"]:
        lines.append(f"  Contains expected key: `{DASHBOARD_JS_BUILD_KEY}`")
    lines.append("")

    # Trace Smoke
    lines.append("## Trace Smoke")
    tr = report["checks"]["trace"]
    lines.append(f"- {_emoji(tr['ok'])} POST /api/trace → {'200' if tr['details'].get('posted') else 'FAIL'}")
    if tr["details"].get("found_in_file"):
        lines.append("  Event found in trace file")
    lines.append("")

    # Sample Run
    lines.append("## Sample Run")
    sr = report["checks"]["sample_run"]
    lines.append(f"- {_emoji(sr['ok'])} Verdict API for `{report['sample_run_id']}`")
    lines.append("")

    # Blockers
    lines.append("## Blockers")
    if report["blockers"]:
        for b in report["blockers"]:
            lines.append(f"- :x: {b}")
    else:
        lines.append("- None :tada:")
    lines.append("")

    # Warnings
    lines.append("## Warnings")
    if report["warnings"]:
        for w in report["warnings"]:
            lines.append(f"- :warning: {w}")
    else:
        lines.append("- None")
    lines.append("")

    # Release Freeze Decision
    lines.append("## Release Freeze Decision")
    if overall == "pass":
        lines.append(f"**RECOMMENDATION: PROCEED** — All {report['pass_count']} checks passed with 0 blockers.")
    elif overall == "fail":
        lines.append(f"**RECOMMENDATION: BLOCKED** — {report['fail_count']} checks failed with {len(report['blockers'])} blockers.")
    else:
        lines.append(f"**RECOMMENDATION: HOLD** — Status is blocked, manual review required.")
    lines.append("")
    lines.append("---")
    lines.append(f"*Report generated by P8 release_readiness.py at {report['generated_at']}*")

    return "\n".join(lines)


def generate(
    runs_dir: str,
    vault_dir: str,
    run_id: str,
    port: int,
    trace_path: str,
) -> dict:
    # Set API_BASE for checkers
    import regression_harness as rh
    rh.API_BASE = f"http://127.0.0.1:{port}"

    checks: dict[str, dict] = {}
    checks["files"] = check_files(runs_dir, vault_dir, run_id)
    checks["apis"] = check_apis(run_id)
    checks["dashboard_build"] = check_dashboard_build(PRODUCT_DIR)
    checks["trace"] = check_trace(trace_path)
    checks["sample_run"] = check_sample_run(run_id)

    pass_count = sum(1 for c in checks.values() if c.get("ok"))
    fail_count = len(checks) - pass_count
    blockers: list[str] = []
    warnings: list[str] = []
    for c in checks.values():
        blockers.extend(c.get("blockers", []))
        warnings.extend(c.get("warnings", []))

    overall = "pass" if not blockers else "fail"

    build_id = checks["dashboard_build"].get("details", {}).get("build_id", "")

    return {
        "schema_version": READINESS_SCHEMA,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "overall_status": overall,
        "checks": {k: _build_check_summary(v) for k, v in checks.items()},
        "pass_count": pass_count,
        "fail_count": fail_count,
        "blockers": blockers,
        "warnings": warnings,
        "sample_run_id": run_id,
        "build_id": build_id,
    }


def main():
    parser = argparse.ArgumentParser(description="P8 Release Readiness Report")
    parser.add_argument("--runs-dir", required=True)
    parser.add_argument("--vault-dir", required=True)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--port", type=int, required=True)
    parser.add_argument("--trace", required=True)
    args = parser.parse_args()

    report = generate(
        runs_dir=args.runs_dir,
        vault_dir=args.vault_dir,
        run_id=args.run_id,
        port=args.port,
        trace_path=args.trace,
    )

    # Write JSON
    json_path = Path(args.runs_dir) / "release-readiness.json"
    json_path.write_text(
        json.dumps(report, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"  Wrote: {json_path}")

    # Write MD
    vault_indexes = Path(args.vault_dir) / "Indexes"
    vault_indexes.mkdir(parents=True, exist_ok=True)
    md_path = vault_indexes / "release-readiness.md"
    md_content = _build_markdown(report)
    md_path.write_text(md_content, encoding="utf-8")
    print(f"  Wrote: {md_path}")

    print()
    print(f"Overall: {report['overall_status'].upper()}")
    print(f"  Pass: {report['pass_count']}  Fail: {report['fail_count']}")
    print(f"  Blockers: {len(report['blockers'])}  Warnings: {len(report['warnings'])}")

    sys.exit(0 if report["overall_status"] == "pass" else 1)


if __name__ == "__main__":
    main()
